//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Handler.rc
//
#define IDR_MANIFEST                    1
#define IDEXIT                          3
#define IDD_ABOUTBOX                    100
#define IDD_HANDLER_FORM                101
#define IDD_DIALOG_ABOUT                102
#define IDD_DIALOG_EXIT                 103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDD_DIALOG_COLOR                105
#define IDD_DIALOG_INFOR                106
#define IDD_DIALOG_KEYPAD               107
#define IDD_DIALOG_MESSAGE              108
#define IDD_DIALOG_KEYBOARD             109
#define IDD_DIALOG_MENU                 110
#define IDD_DIALOG_MULTI_MSG            111
#define IDD_DIALOG_SELECT               112
#define IDD_DIALOG_PASS_CHANGE          113
#define IDD_DIALOG_PASS_CHECK           114
#define IDD_DIALOG_ALARM                115
#define IDD_SCREEN_BASIC1               117
#define IDD_SCREEN_DATA_VIEW            121
#define IDD_MOTOR_AXIS_1                123
#define IDD_MOTOR_AXIS_2                124
#define IDD_MOTOR_AXIS_3                125
#define IDD_MOTOR_AXIS_4                126
#define IDD_MOTOR_AXIS_5                127
#define IDR_MAINFRAME                   128
#define IDR_HANDLETYPE                  129
#define IDD_SCREEN_MAIN                 130
#define IDC_GROUP_LOT_TIME              130
#define IDD_DIALOG_LIST                 131
#define IDD_DIALOG_TITLE                132
#define IDD_MOTOR_AXIS_6                133
#define IDR_EMPTY                       134
#define IDD_MOTOR_AXIS_7                135
#define IDB_TOOLBAR_DRAW                136
#define IDD_MOTOR_AXIS_8                137
#define IDD_MOTOR_AXIS_9                138
#define IDD_MOTOR_AXIS_10               139
#define IDB_TOOLBAR_DRAW_HOT            140
#define IDD_MOTOR_PART                  141
#define IDD_DIALOG_PART_IO              142
#define IDD_SCREEN_MOTOR                143
#define IDB_TOOLBAR_DRAW_DISABLED       152
#define IDR_GIF_N_LOGO                  153
#define IDB_CLOCKST_BIG                 157
#define IDB_CLOCKST_PANE                158
#define IDB_CLOCKST_SMALL               159
#define IDD_SCREEN_BASIC                160
#define IDD_SCREEN_IO                   162
#define IDD_SCREEN_INITIAL              163
#define IDD_SCREEN_ADMIN                164
#define IDD_SCREEN_LIST_OPERATION       165
#define IDD_SCREEN_LIST_DATA_VIEW       166
#define IDD_SCREEN_LOCK                 167
#define IDD_SCREEN_SET_MAINTENANCE      168
#define IDD_SCREEN_WAIT_TIME            169
#define IDD_SCREEN_SET_INTERFACE        170
#define IDD_SCREEN_MOTOR_SPEED          171
#define IDR_GIF_EXIT                    172
#define IDC_BTN_ALARM_RESET_1           172
#define IDR_GIF_CHOICE                  173
#define IDC_BTN_ALARM_RESET_2           173
#define IDB_BIG3                        174
#define IDC_BTN_ALARM_RESET_3           174
#define IDR_GIF_MSG                     175
#define IDC_BTN_ALARM_RESET_4           175
#define IDR_GIF_MENU                    176
#define IDC_BTN_ALARM_RESET_5           176
#define IDI_MAINTENANCE                 177
#define IDI_TRAY                        178
#define IDI_MOT_POS                     179
#define IDI_MOT_SPD                     180
#define IDI_LIST_ARM                    181
#define IDI_LIST_WORK                   182
#define IDI_OPEN_FOLDER                 183
#define IDB_REDBUTTON                   184
#define IDI_GRAY_LED_ICON               185
#define IDI_RED_LED_ICON                186
#define IDC_BTN_BARCODE_TEST            186
#define IDI_GREEN_LED_ICON              187
#define IDC_BTN_BASIC_APPLY             187
#define IDB_GREENBUTTON                 188
#define IDC_BTN_BASIC_CANCEL            188
#define IDC_BTN_BASIC_CANCLE            188
#define IDR_GIF_ALARM                   189
#define IDC_BTN_BASIC_RELOAD            189
#define IDC_BTN_BOARD_0                 190
#define IDB_MATRIXSMALL                 190
#define IDC_BTN_BOARD_1                 191
#define IDB_MATRIXTINY                  191
#define IDC_BTN_BOARD_2                 192
#define IDB_MATRIXLARGE                 192
#define IDC_BTN_BOARD_3                 193
#define IDB_DIGITSTEX_BLACK             193
#define IDC_BTN_BOARD_4                 194
#define IDB_DIGITSTEX_CYAN              194
#define IDC_BTN_BOARD_5                 195
#define IDB_DIGITSTEX_GREEN             195
#define IDC_BTN_BOARD_6                 196
#define IDB_DIGITSTEX_YELLOW            196
#define IDC_BTN_BOARD_7                 197
#define IDB_DIGITSTEX_RED               197
#define IDC_BTN_BOARD_8                 198
#define IDC_BTN_BOARD_9                 199
#define IDB_DIGITSTEX_DISABLE           199
#define IDC_BTN_BOARD_A                 200
#define IDB_DIGITSTEX_BBLACK            200
#define IDC_BTN_BOARD_ADD               201
#define IDB_DIGITSTEX_BCYAN             201
#define IDC_BTN_BOARD_B                 202
#define IDB_DIGITSTEX_BGREEN            202
#define IDC_BTN_BOARD_BACK              203
#define IDB_DIGITSTEX_BYELLOW           203
#define IDC_BTN_BOARD_C                 204
#define IDB_DIGITSTEX_BRED              204
#define IDC_BTN_BOARD_D                 205
#define IDB_DIGITSTEX_BBLUE             205
#define IDC_BTN_BOARD_DEL               206
#define IDC_BTN_BOARD_DIV               207
#define IDB_DIGITSTEX_BDISABLE          207
#define IDC_BTN_BOARD_DOLLAR            208
#define IDB_DIGITSTEX_BBDISABLE         208
#define IDC_BTN_BOARD_DOT               209
#define IDB_DIGITSTEX_SBDISABLE         209
#define IDC_BTN_BOARD_E                 210
#define IDI_SOUND_ON                    210
#define IDC_BTN_BOARD_F                 211
#define IDI_SOUND_OFF                   211
#define IDC_BTN_BOARD_G                 212
#define IDI_KEYBOARD                    212
#define IDC_BTN_BOARD_H                 213
#define IDR_GIF_LOCK                    213
#define IDC_BTN_BOARD_I                 214
#define IDC_BTN_BOARD_J                 215
#define IDD_SCREEN_MOTOR_TEACH          215
#define IDC_BTN_BOARD_K                 216
#define IDI_MODULE                      216
#define IDC_BTN_BOARD_L                 217
#define IDD_SCREEN_SET_TESTREFERENECE   217
#define IDC_BTN_BOARD_LBRACE_B          218
#define IDI_N_DOWN                      218
#define IDC_BTN_BOARD_LBRACE_S          219
#define IDI_N_UP                        219
#define IDC_BTN_BOARD_LINE              220
#define IDI_N_LEFT                      220
#define IDC_BTN_BOARD_M                 221
#define IDI_N_RIGHT                     221
#define IDC_BTN_BOARD_N                 222
#define IDR_GIF_INITIALIZING            222
#define IDC_BTN_BOARD_O                 223
#define IDB_INITIAL_STR_1               223
#define IDC_BTN_BOARD_P                 224
#define IDB_INITIAL_STR_2               224
#define IDC_BTN_BOARD_Q                 225
#define IDD_DIALOG_EVENT_MSG            225
#define IDC_BTN_BOARD_R                 226
#define IDC_BTN_BOARD_RBRACE_B          227
#define IDB_DATEPICKER_BUTTON           227
#define IDC_BTN_BOARD_RBRACE_S          228
#define IDC_CURSOR1                     228
#define IDC_BTN_BOARD_S                 229
#define IDD_DIALOG1                     229
#define IDD_DIALOG_TRACK_OUT            229
#define IDC_BTN_BOARD_SHARP             230
#define IDC_BTN_BOARD_T                 231
#define IDC_CURSOR2                     231
#define IDC_BTN_BOARD_U                 232
#define IDI_EMG_STOP                    232
#define IDC_BTN_BOARD_V                 233
#define IDI_LEFT                        233
#define IDC_BTN_BOARD_W                 234
#define IDI_RIGHT                       234
#define IDC_BTN_BOARD_X                 235
#define IDI_DN                          235
#define IDC_BTN_BOARD_Y                 236
#define IDI_UP                          236
#define IDC_BTN_BOARD_Z                 237
#define IDI_HOME                        237
#define IDI_EXIT                        238
#define IDI_IO                          239
#define IDI_MOTOR                       240
#define IDD_DIALOG_PART_MANUAL          241
#define IDD_DIALOG_BUFFER_STATUS        244
#define IDD_DIALOG_SCRAP_INFO_VIEW      245
#define IDC_BTN_BUZZER_OFF              248
#define IDD_DIALOG_ADD_FAIL             248
#define IDC_BTN_DATA_BACKUP             251
#define IDD_SCREEN_FILE_EDITOR          251
#define IDC_BTN_STEP_SAVE               252
#define IDC_BTN_DELETE                  253
#define IDC_BTN_FTP_CONNECT_TEST        259
#define IDC_BTN_FTPID_SAVE              260
#define IDC_BTN_FTPIP_SAVE              261
#define IDC_BTN_FTPPASSWORD_SAVE        262
#define IDC_BTN_FTPPORT_SAVE            263
#define IDC_BTN_HOMING_1                314
#define IDC_BTN_HOMING_2                315
#define IDC_BTN_HOMING_3                316
#define IDC_BTN_HOMING_4                317
#define IDC_BTN_HOMING_5                318
#define IDC_BTN_I_GRID                  320
#define IDC_BTN_I_GRID2                 321
#define IDC_BTN_I_TEXT                  322
#define IDC_BTN_I_TEXT2                 323
#define IDC_BTN_MAINTENANCE_APPLY       352
#define IDC_BTN_MS_APPLY                356
#define IDC_BTN_O_GRID                  360
#define IDC_BTN_O_GRID2                 361
#define IDC_BTN_O_TEXT                  362
#define IDC_BTN_O_TEXT2                 363
#define IDC_BTN_OPERATION_FILE_DEL      367
#define IDC_BTN_OPERATION_FILE_REFRESH  368
#define IDC_BTN_PAD_0                   369
#define IDC_BTN_PAD_1                   370
#define IDC_BTN_PAD_10                  371
#define IDC_BTN_PAD_100                 372
#define IDC_BTN_PAD_1000                373
#define IDC_BTN_PAD_1001                374
#define IDC_BTN_PAD_101                 375
#define IDC_BTN_PAD_11                  376
#define IDC_BTN_PAD_2                   377
#define IDC_BTN_PAD_3                   378
#define IDC_BTN_PAD_4                   379
#define IDC_BTN_PAD_5                   380
#define IDC_BTN_PAD_6                   381
#define IDC_BTN_PAD_7                   382
#define IDC_BTN_PAD_8                   383
#define IDC_BTN_PAD_9                   384
#define IDC_BTN_PAD_BACK                385
#define IDC_BTN_PAD_DEL                 386
#define IDC_BTN_PAD_DOT                 387
#define IDC_BTN_PARTIAL_NO              388
#define IDC_BTN_PAD_RESET               388
#define IDC_BTN_PARTIAL_YES             389
#define IDC_BTN_PASS_CHG_0              390
#define IDC_BTN_PASS_CHG_1              391
#define IDC_BTN_PASS_CHG_2              392
#define IDC_BTN_PASS_CHG_3              393
#define IDC_BTN_PASS_CHG_4              394
#define IDC_BTN_PASS_CHG_5              395
#define IDC_BTN_PASS_CHG_6              396
#define IDC_BTN_PASS_CHG_7              397
#define IDC_BTN_PASS_CHG_8              398
#define IDC_BTN_PASS_CHG_9              399
#define IDC_BTN_PASS_CHG_A              400
#define IDC_BTN_PASS_CHG_ADD            401
#define IDC_BTN_PASS_CHG_B              402
#define IDC_BTN_PASS_CHG_BACK           403
#define IDC_BTN_PASS_CHG_C              404
#define IDC_BTN_PASS_CHG_D              405
#define IDC_BTN_PASS_CHG_DEL            406
#define IDC_BTN_PASS_CHG_DIV            407
#define IDC_BTN_PASS_CHG_DOLLAR         408
#define IDC_BTN_PASS_CHG_DOT            409
#define IDC_BTN_PASS_CHG_E              410
#define IDC_BTN_PASS_CHG_F              411
#define IDC_BTN_PASS_CHG_G              412
#define IDC_BTN_PASS_CHG_H              413
#define IDC_BTN_PASS_CHG_I              414
#define IDC_BTN_PASS_CHG_J              415
#define IDC_BTN_PASS_CHG_K              416
#define IDC_BTN_PASS_CHG_L              417
#define IDC_BTN_PASS_CHG_LBRACE_B       418
#define IDC_BTN_PASS_CHG_LBRACE_S       419
#define IDC_BTN_PASS_CHG_LINE           420
#define IDC_BTN_PASS_CHG_M              421
#define IDC_BTN_PASS_CHG_N              422
#define IDC_BTN_PASS_CHG_O              423
#define IDC_BTN_PASS_CHG_P              424
#define IDC_BTN_PASS_CHG_Q              425
#define IDC_BTN_PASS_CHG_R              426
#define IDC_BTN_PASS_CHG_RBRACE_B       427
#define IDC_BTN_PASS_CHG_RBRACE_S       428
#define IDC_BTN_PASS_CHG_S              429
#define IDC_BTN_PASS_CHG_SHARP          430
#define IDC_BTN_PASS_CHG_T              431
#define IDC_BTN_PASS_CHG_U              432
#define IDC_BTN_PASS_CHG_V              433
#define IDC_BTN_PASS_CHG_W              434
#define IDC_BTN_PASS_CHG_X              435
#define IDC_BTN_PASS_CHG_Y              436
#define IDC_BTN_PASS_CHG_Z              437
#define IDC_BTN_PASS_CHK_0              438
#define IDC_BTN_PASS_CHK_1              439
#define IDC_BTN_PASS_CHK_2              440
#define IDC_BTN_PASS_CHK_3              441
#define IDC_BTN_PASS_CHK_4              442
#define IDC_BTN_PASS_CHK_5              443
#define IDC_BTN_PASS_CHK_6              444
#define IDC_BTN_PASS_CHK_7              445
#define IDC_BTN_PASS_CHK_8              446
#define IDC_BTN_PASS_CHK_9              447
#define IDC_BTN_PASS_CHK_A              448
#define IDC_BTN_PASS_CHK_ADD            449
#define IDC_BTN_PASS_CHK_B              450
#define IDC_BTN_PASS_CHK_BACK           451
#define IDC_BTN_PASS_CHK_C              452
#define IDC_BTN_PASS_CHK_D              453
#define IDC_BTN_PASS_CHK_DEL            454
#define IDC_BTN_PASS_CHK_DIV            455
#define IDC_BTN_PASS_CHK_DOLLAR         456
#define IDC_BTN_PASS_CHK_DOT            457
#define IDC_BTN_PASS_CHK_E              458
#define IDC_BTN_PASS_CHK_F              459
#define IDC_BTN_PASS_CHK_G              460
#define IDC_BTN_PASS_CHK_H              461
#define IDC_BTN_PASS_CHK_I              462
#define IDC_BTN_PASS_CHK_J              463
#define IDC_BTN_PASS_CHK_K              464
#define IDC_BTN_PASS_CHK_L              465
#define IDC_BTN_PASS_CHK_LBRACE_B       466
#define IDC_BTN_PASS_CHK_LBRACE_S       467
#define IDC_BTN_PASS_CHK_LINE           468
#define IDC_BTN_PASS_CHK_M              469
#define IDC_BTN_PASS_CHK_N              470
#define IDC_BTN_PASS_CHK_O              471
#define IDC_BTN_PASS_CHK_P              472
#define IDC_BTN_PASS_CHK_Q              473
#define IDC_BTN_PASS_CHK_R              474
#define IDC_BTN_PASS_CHK_RBRACE_B       475
#define IDC_BTN_PASS_CHK_RBRACE_S       476
#define IDC_BTN_PASS_CHK_S              477
#define IDC_BTN_PASS_CHK_SHARP          478
#define IDC_BTN_PASS_CHK_T              479
#define IDC_BTN_PASS_CHK_U              480
#define IDC_BTN_PASS_CHK_V              481
#define IDC_BTN_PASS_CHK_W              482
#define IDC_BTN_PASS_CHK_X              483
#define IDC_BTN_PASS_CHK_Y              484
#define IDC_BTN_PASS_CHK_Z              485
#define IDC_BTN_PASSWORD_CHANGE_LEVLE1  486
#define IDC_BTN_PASSWORD_CHANGE_LEVLE2  487
#define IDC_BTN_POWER_OFF_1             503
#define IDC_BTN_POWER_OFF_2             504
#define IDC_BTN_POWER_OFF_3             505
#define IDC_BTN_POWER_OFF_4             506
#define IDC_BTN_POWER_OFF_5             507
#define IDC_BTN_POWER_ON_1              509
#define IDC_BTN_POWER_ON_2              510
#define IDC_BTN_POWER_ON_3              511
#define IDC_BTN_POWER_ON_4              512
#define IDC_BTN_POWER_ON_5              513
#define IDC_BTN_PREV_ALARM_1            522
#define IDC_BTN_PREV_ALARM_10           523
#define IDC_BTN_PREV_ALARM_2            524
#define IDC_BTN_PREV_ALARM_3            525
#define IDC_BTN_PREV_ALARM_4            526
#define IDC_BTN_PREV_ALARM_5            527
#define IDC_BTN_PREV_ALARM_6            528
#define IDC_BTN_PREV_ALARM_7            529
#define IDC_BTN_PREV_ALARM_8            530
#define IDC_BTN_PREV_ALARM_9            531
#define IDC_BTN_SEARCH                  592
#define IDC_BTN_SEARCH_GROUND           593
#define IDC_BTN_SEARCH_HIFIX            594
#define IDC_BTN_BUFFER_SEARCH           594
#define IDC_BTN_SEARCH_ALARM            595
#define IDC_BTN_SEARCH_SOCKETOFF        596
#define IDC_BTN_SEARCH_TIME             597
#define IDC_BTN_TESTER_CONNECT          637
#define IDC_BTN_CONNECT_NMACHINE        637
#define IDC_BTN_CONNECT_ECSERVER        637
#define IDC_BTN_TESTERIP_SAVE           638
#define IDC_BTN_IP_SAVE_NMACHINE        638
#define IDC_BTN_IP_SAVE_ECSERVER        638
#define IDC_BTN_TESTERPORT_SAVE         639
#define IDC_BTN_PORT_SAVE_NMACHINE      639
#define IDC_BTN_PORT_SAVE_ECSERVER      639
#define IDC_BTN_IP_SAVE_BPC             640
#define IDC_BTN_LDPORT_SAVE_ECSERVER    640
#define IDC_BTN_PORT_SAVE_BPC           641
#define IDC_BTN_IP_SAVE_ECSERVER2       641
#define IDC_BTN_IP_SAVE_NEXT            641
#define IDC_BTN_CONNECT_BPC             642
#define IDC_BTN_PORT_SAVE_ECSERVER2     642
#define IDC_BTN_PORT_SAVE_NEXT          642
#define IDC_BTN_CONNECT_ECSERVER2       643
#define IDC_BTN_CONNECT_NEXT            643
#define IDC_BTN_GROUND_TEST             703
#define IDC_BTN_ELECTROSTATIC_TEST      703
#define IDC_BTN_SAVE                    703
#define IDC_BTN_DAY_PREV                704
#define IDC_BTN_START_TIME              705
#define IDC_BTN_END_TIME                706
#define IDC_BTN_VIEW                    707
#define IDC_BTN_VIEW_PRIME              708
#define IDC_BTN_VIEW_RETEST             709
#define IDC_BTN_DAY_NEXT                710
#define IDC_BTN_DAY_TODAY               711
#define IDC_CHK_BARCODE                 723
#define IDC_CHK_BARCODE_ERROR_MODE      724
#define IDC_CHK_REVERSE                 724
#define IDC_CHK_BYPASS                  725
#define IDC_CHK_ULD_CONVAYOR            725
#define IDC_CHK_NTO_FAIL                726
#define IDC_CHK_VIRTUAL                 727
#define IDC_CHK_HTO_FAIL                729
#define IDC_CHK_BTO_FAIL                730
#define IDC_CHK_BUZZER                  732
#define IDC_CHK_INTERFACE               738
#define IDC_CHK_RETEST                  752
#define IDC_CUSTOM_DATA                 831
#define IDC_CUSTOM_DEVICE               832
#define IDC_CUSTOM_LOT                  835
#define IDC_CUSTOM_MOTOR_SPEED          842
#define IDC_DATA_ALARM_CODE             843
#define IDC_CUSTOM_MOTOR_VARIABLE_SPEED 843
#define IDC_DATA_ALARM_TYPE             844
#define IDC_DATA_ALARM_TIME             845
#define IDC_DGT_BARCODE_READ_CNT        951
#define IDC_DGT_BARCODE_READ_ERR_CNT    952
#define IDC_MSG_GROUND_1                953
#define IDC_MSG_ELECTROSTATIC_1         953
#define IDC_MSG_GROUND_2                954
#define IDC_MSG_ELECTROSTATIC_2         954
#define IDC_MSG_GROUND_3                955
#define IDC_MSG_ELECTROSTATIC_3         955
#define IDC_MSG_GROUND_4                956
#define IDC_MSG_ELECTROSTATIC_4         956
#define IDC_DGT_CURRENT_POS_1           956
#define IDC_MSG_GROUND_5                957
#define IDC_MSG_ELECTROSTATIC_5         957
#define IDC_DGT_CURRENT_POS_2           957
#define IDC_LABEL_ELECTROSTATIC_1       958
#define IDC_DGT_CURRENT_POS_3           958
#define IDC_DGT_CURRENT_POS_4           959
#define IDC_DGT_CURRENT_POS_5           960
#define IDC_LABEL_ELECTROSTATIC_2       963
#define IDC_LABEL_ELECTROSTATIC_3       964
#define IDC_LABEL_ELECTROSTATIC_4       965
#define IDC_LABEL_ELECTROSTATIC_5       966
#define IDC_DGT_FLICKER_TIME            976
#define IDC_DGT_CHANGE_TIME             977
#define IDC_MSG_FORM_NAME               1000
#define IDC_MSG_STATUS_INFO             1001
#define IDC_GIF_TITLE_LOGO              1002
#define IDC_LIST_CLOCK                  1003
#define IDC_TITLE_INTERFACE_MODE        1003
#define IDC_BUTTON1                     1004
#define IDC_TITLE_DEVICE_MODE           1004
#define IDC_BTN_MOTTEACH_APPLY          1004
#define IDC_BTN_WAIT_APPLY              1004
#define IDC_BTN_RACK_POWER_1            1004
#define IDC_BTN_BUFFER_READY_TEST       1004
#define IDC_BTN_MOTOR_MOVE_1            1004
#define IDC_BTN_LENGTH_CHANGE           1004
#define IDC_BTN_YES                     1004
#define IDC_MSG_OLD_VALUE               1005
#define IDC_TITLE_BARCODE_MODE          1005
#define IDC_BTN_WAIT_CANCEL             1005
#define IDC_BTN_RACK_POWER_2            1005
#define IDC_BTN_BUFFER_IN_TEST          1005
#define IDC_BUTTON2                     1005
#define IDC_BTN_REAR_BUFFER             1005
#define IDC_BTN_MOTOR_MOVE_2            1005
#define IDC_TITLE_FRONT_KEY             1005
#define IDC_MSG_NEW_VALUE               1006
#define IDC_TITLE_SOCKETOFF_MODE        1006
#define IDC_BTN_RACK_POWER_3            1006
#define IDC_BTN_SOCKET_CHK_TEST         1006
#define IDC_BUTTON3                     1006
#define IDC_BTN_RETEST                  1006
#define IDC_BTN_MOTOR_MOVE_3            1006
#define IDC_TITLE_REAR_KEY              1006
#define IDC_EDIT_KEYPAD_TITLE           1007
#define IDC_TITLE_LEVEL_MODE            1007
#define IDC_BTN_RACK_POWER_4            1007
#define IDC_BTN_APCT_SOCKET_INFO_TEST   1007
#define IDC_BUTTON4                     1007
#define IDC_BTN_FRONT_BUFFER            1007
#define IDC_BTN_MOTOR_MOVE_4            1007
#define IDC_CUSTOM_LIST                 1008
#define IDC_BTN_APCT_BLOT_TEST          1008
#define IDC_BTN_MOTOR_MOVE_5            1008
#define IDC_TITLE_RETEST_MODE           1008
#define IDC_CUSTOM_IO                   1009
#define IDC_BTN_MOTOR_MOVE_6            1009
#define IDC_BTN_SLAVE_ENABLE            1010
#define IDC_BTN_MOTOR_MOVE_7            1010
#define IDC_BTN_PICKER_INFO             1011
#define IDC_BTN_MOTOR_MOVE_8            1011
#define IDC_GROUP_CONTI_OP              1012
#define IDC_BTN_REJECT_BUFFER           1012
#define IDC_BTN_MOTOR_MOVE_9            1012
#define IDC_BTN_MOTOR_MOVE_10           1013
#define IDC_RADIO_IO_CNT_1              1014
#define IDC_BTN_UPPER_TRAY              1014
#define IDC_BTN_MOTOR_MOVE_11           1014
#define IDC_RADIO_IO_CNT_10             1015
#define IDC_BTN_LOWER_TRAY              1015
#define IDC_BTN_MOTOR_MOVE_12           1015
#define IDC_RADIO_IO_CNT_50             1016
#define IDC_BTN_LOB_TRAY                1016
#define IDC_RADIO_IO_CNT_100            1017
#define IDC_BTN_IO_E_STOP               1018
#define IDC_DGT_RETRY_WAIT              1019
#define IDC_MSG_RETRY_WAIT              1020
#define IDC_MSG_LOCK                    1021
#define IDC_GIF_LOCK                    1022
#define IDC_BTN_UNLOCK                  1023
#define IDC_BTN_MOTOR_SPEED             1023
#define IDC_TAB_MOTOR                   1024
#define IDC_CST_X_LD_BUFFER             1025
#define IDC_CST_X_SITE_1                1026
#define IDC_CST_X_SITE_2                1027
#define IDC_LIST_DATA                   1027
#define IDC_CST_X_SITE_3                1028
#define IDC_GROUP_REAR_IN_BUFFER        1028
#define IDC_CST_X_SITE_4                1029
#define IDC_GROUP_FRONT_IN_BUFFER       1029
#define IDC_CST_X_ULD_BUFFER            1030
#define IDC_GROUP_REAR_OUT_BUFFER       1030
#define IDC_BTN_IO_SAVE                 1030
#define IDC_CST_P_EJECT                 1031
#define IDC_GROUP_FRONT_OUT_BUFFER      1031
#define IDC_BTN_IO_PART_SAVE            1031
#define IDC_CST_P_PICK                  1032
#define IDC_GROUP_REAR_SHIFTER          1032
#define IDC_BTN_MOTOR_PART_SAVE         1032
#define IDC_CST_P_PLACE                 1033
#define IDC_GROUP_FRONT_SHIFTER         1033
#define IDC_DGT_MANUAL_RATE             1033
#define IDC_BTN_INIT_RETRY              1033
#define IDC_BTN_MOTOR_POS_SAVE          1033
#define IDC_CST_Z_SAFETY                1034
#define IDC_GROUP_FRONT_RACK_1          1034
#define IDC_RADIO_IO_BD                 1034
#define IDC_BTN_TIME_SAVE               1034
#define IDC_CST_Z_EJECT                 1035
#define IDC_GROUP_REAR_RACK_1           1035
#define IDC_RADIO_MOT_BD                1035
#define IDC_CST_Z_PLACE                 1036
#define IDC_GROUP_REAR_RACK_2           1036
#define IDC_CST_Z_PICK                  1037
#define IDC_GROUP_FRONT_RACK_2          1037
#define IDC_CST_BUFFER_IN               1038
#define IDC_GROUP_TIME_INFO             1038
#define IDC_CST_BUFFER_OUT              1039
#define IDC_GROUP_TEST_TIME             1039
#define IDC_CST_BARCODE_REAR            1040
#define IDC_GROUP_WORK_COUNT            1040
#define IDC_BTN_INIT_SKIP               1040
#define IDC_CST_BARCODE_FRONT           1041
#define IDC_GROUP_BIN_COUNT             1041
#define IDC_GROUP_TEST_COUNT            1042
#define IDC_CST_BARCODE_SAFETY          1042
#define IDC_GROUP_CONTROL_PANEL         1043
#define IDC_GIF_INITIALIZING            1043
#define IDC_CST_Z_PRESS                 1043
#define IDC_CST_REAR_IN_BUFFER          1044
#define IDC_MSG_INITIAL                 1044
#define IDC_CST_Z_BUFFER_PLACE          1044
#define IDC_DGT_NEW_VALUE               1045
#define IDC_CST_FRONT_IN_BUFFER         1045
#define IDC_CST_Z_BUFFER_PICK           1045
#define IDC_DGT_OLD_VALUE               1046
#define IDC_CST_REAR_SHIFTER            1046
#define IDC_CST_FRONT_SHIFTER           1047
#define IDC_CST_REAR_OUT_BUFFER         1048
#define IDC_CST_FRONT_OUT_BUFFER        1049
#define IDC_DGT_PCB_SIZE_X              1049
#define IDC_CST_REAR_RACK_1_L           1050
#define IDC_DGT_PCB_SIZE_Y              1050
#define IDC_CST_REAR_RACK_1_R           1051
#define IDC_CST_REAR_RACK_2_L           1052
#define IDC_BTN_APPLY                   1052
#define IDC_CST_REAR_RACK_2_R           1053
#define IDC_CST_COUNT_BIN               1054
#define IDC_CST_COUNT_TEST              1055
#define IDC_CST_FRONT_RACK_1_L          1056
#define IDC_CST_FRONT_RACK_1_R          1057
#define IDC_CST_FRONT_RACK_2_L          1058
#define IDC_CST_FRONT_RACK_2_R          1059
#define IDC_CST_COUNT_WORK              1061
#define IDC_BTN_EMG                     1064
#define IDC_CUSTOM_MOTOR                1068
#define IDC_DGT_RUN_TIME                1069
#define IDC_DGT_WRUN_TIME               1070
#define IDC_DGT_BRUN_TIME               1071
#define IDC_DGT_RETEST_COUNT            1071
#define IDC_DGT_STOP_TIME               1072
#define IDC_DGT_ALARM_TIME              1073
#define IDC_MSG_RUN_TIME                1074
#define IDC_MSG_WRUN_TIME               1075
#define IDC_MSG_BRUN_TIME               1076
#define IDC_MSG_STOP_TIME               1077
#define IDC_MSG_ALARM_TIME              1078
#define IDC_DGT_RUN_RATE                1078
#define IDC_MSG_INDEX_TIME_FRONT_RACK_1_L 1079
#define IDC_MSG_INDEX_TIME_FRONT_RACK_1_R 1080
#define IDC_MSG_INDEX_TIME_FRONT_RACK_2_L 1081
#define IDC_MSG_INDEX_TIME_FRONT_RACK_2_R 1082
#define IDC_MSG_INDEX_TIME_REAR_RACK_1_L 1083
#define IDC_MSG_INDEX_TIME_REAR_RACK_1_R 1084
#define IDC_MSG_INDEX_TIME_REAR_RACK_2_L 1085
#define IDC_MSG_INDEX_TIME_REAR_RACK_2_R 1086
#define IDC_DGT_P_INDEX_TIME_FRONT_RACK_1_L 1087
#define IDC_DGT_P_INDEX_TIME_FRONT_RACK_1_R 1088
#define IDC_DGT_P_INDEX_TIME_FRONT_RACK_2_L 1089
#define IDC_DGT_P_INDEX_TIME_FRONT_RACK_2_R 1090
#define IDC_DGT_P_INDEX_TIME_REAR_RACK_1_L 1091
#define IDC_DGT_P_INDEX_TIME_REAR_RACK_1_R 1092
#define IDC_DGT_P_INDEX_TIME_REAR_RACK_2_L 1093
#define IDC_DGT_P_INDEX_TIME_REAR_RACK_2_R 1094
#define IDC_MSG_P_INDEX_TIME_FRONT_RACK_1_L 1095
#define IDC_MSG_P_INDEX_TIME_FRONT_RACK_1_R 1096
#define IDC_MSG_P_INDEX_TIME_FRONT_RACK_2_R 1097
#define IDC_DGT_STAMP_LIMIT             1097
#define IDC_MSG_P_INDEX_TIME_FRONT_RACK_2_L 1098
#define IDC_DGT_STATIC_ELECTRICITY_CHECK_GAP 1098
#define IDC_MSG_P_INDEX_TIME_REAR_RACK_1_L 1099
#define IDC_DGT_GROUND_VALUE            1099
#define IDC_MSG_P_INDEX_TIME_REAR_RACK_1_R 1100
#define IDC_DGT_GROUND_ALLOW            1100
#define IDC_MSG_P_INDEX_TIME_REAR_RACK_2_L 1101
#define IDC_DGT_STAMP_CHECK             1101
#define IDC_MSG_P_INDEX_TIME_REAR_RACK_2_R 1102
#define IDC_DGT_GROUND_RESULT1          1102
#define IDC_BTN_DOOR_OPEN               1103
#define IDC_DGT_GROUND_RESULT2          1103
#define IDC_BTN_LOT_CANCEL              1104
#define IDC_DGT_GROUND_RESULT3          1104
#define IDC_GROUP_INFO_SELECT           1105
#define IDC_DGT_GROUND_RESULT4          1105
#define IDC_RADIO_TEST_TIME             1106
#define IDC_DGT_GROUND_RESULT5          1106
#define IDC_RADIO_BOARD_INFO            1107
#define IDC_GROUP_RUN_MODE              1107
#define IDC_RADIO_RUN_MODE_ONLINE       1108
#define IDC_RADIO_LOT_INFO              1108
#define IDC_RADIO_RUN_MODE_OFFLINE      1109
#define IDC_RADIO_DEVICE_INFO           1109
#define IDC_GROUP_DEVICE_MODE           1113
#define IDC_RADIO_DEVICE_MODE_USE       1114
#define IDC_RADIO_DEVICE_MODE_NOTUSE    1115
#define IDC_GROUP_RECIPE_SELECT         1116
#define IDC_EDIT_DEVICE_TYPE            1117
#define IDC_LIST1                       1118
#define IDC_BTN_DVC_DELETE              1119
#define IDC_BTN_DVC_CREATE              1120
#define IDC_GROUP_WORK_MODE             1121
#define IDC_RADIO_WORK_MODE_WORK        1122
#define IDC_RADIO_WORK_MODE_BYPASS      1123
#define IDC_GROUP_ELECTROSTATIC_CHECK_GAP 1124
#define IDC_DGT_ELECTROSTATIC_CHECK_GAP 1125
#define IDC_GROUP_ELECTROSTATIC_CHECK_VALUE 1126
#define IDC_DGT_ELECTROSTATIC_CHECK_VALUE 1127
#define IDC_GROUP_EC_SERVER_SET         1128
#define IDC_GROUP_BPC_SET               1129
#define IDC_GROUP_RETEST_MODE           1129
#define IDC_GROUP_EC_SERVER_SET2        1129
#define IDC_GROUP_NEXT_MACHINE_SET      1129
#define IDC_GROUP_NTO_TIME              1130
#define IDC_RADIO_RETEST_USE            1130
#define IDC_GROUP_BTO_TIME              1131
#define IDC_CST_RACK_REAR_1             1131
#define IDC_CST_RACK_REAR_1_L           1131
#define IDC_RADIO_RETEST_NOTUSE         1131
#define IDC_GROUP_HTO_TIME              1132
#define IDC_CST_RACK_REAR_2             1132
#define IDC_CST_RACK_REAR_2_L           1132
#define IDC_DGT_NTO_TIME                1133
#define IDC_CST_RACK_FRONT_1            1133
#define IDC_CST_RACK_FRONT_1_L          1133
#define IDC_DGT_BTO_TIME                1134
#define IDC_CST_RACK_FRONT_2            1134
#define IDC_CST_RACK_FRONT_2_L          1134
#define IDC_DGT_HTO_TIME                1135
#define IDC_GROUP_AUTO_OFF_MODE         1135
#define IDC_CHK_BOARDOFF_1              1136
#define IDC_RADIO_DEVICE_TYPE_NORMAL    1136
#define IDC_CHK_BOARDOFF_2              1137
#define IDC_RADIO_DEVICE_TYPE_VLPDIMM   1137
#define IDC_CHK_BOARDOFF_3              1138
#define IDC_GROUP_PRESS_COUNT           1138
#define IDC_CHK_BOARDOFF_4              1139
#define IDC_DGT_PRESS_COUNT             1139
#define IDC_CHK_BOARDOFF_5              1140
#define IDC_GROUP_NETWORK_WAIT_TIME     1140
#define IDC_DGT_PICK_COUNT              1140
#define IDC_CHK_BOARDOFF_6              1141
#define IDC_DGT_NETWORK_WAIT_TIME       1141
#define IDC_LABEL_ABSOLUTE_YIELD        1142
#define IDC_GROUP_NETWORK_RETRY_COUNT   1142
#define IDC_LABEL_RELATIVE_YIELD        1143
#define IDC_DGT_NETWORK_RETRY_COUNT     1143
#define IDC_LABEL_CONTINUITY_COUNT      1144
#define IDC_GROUP_HTO_MAX_TIME          1144
#define IDC_GROUP_TRAY_SIZE_SETTING     1144
#define IDC_LABEL_BOARD_APPLY_COUNT     1145
#define IDC_DGT_HTO_MAX_TIME            1145
#define IDC_DGT_TRAY_X                  1145
#define IDC_LABEL_STATION_YIELD         1146
#define IDC_GROUP_BD_LIVE_CHECK_GAP     1146
#define IDC_DGT_TRAY_Y                  1146
#define IDC_LABEL_MACHINE_YIELD         1147
#define IDC_GROUP_RETEST_CALL_MODE      1147
#define IDC_LABEL_LINE_YIELD            1148
#define IDC_RADIO_RETEST_CALL_USE       1148
#define IDC_LABEL_STATION_APPLY_COUNT   1149
#define IDC_RADIO_RETETST_CALL_NOT_USE  1149
#define IDC_GROUP_BOARD_OFF_MODE        1150
#define IDC_GROUP_MLCT_MODE             1150
#define IDC_GROUP_STATION_OFF_MODE      1151
#define IDC_RADIO_MLCT_USE              1151
#define IDC_BTN_TESTREF_APPLY           1152
#define IDC_RADIO_MLCT_NOT_USE          1152
#define IDC_DGT_ABSOLUTE_YIELD          1153
#define IDC_DGT_BD_LIVE_CHECK_GAP       1153
#define IDC_DGT_CONTINUITY_COUNT        1154
#define IDC_GROUP_BOARD_COUNT_MAX       1154
#define IDC_DGT_RELATIVE_YIELD          1155
#define IDC_DGT_BOARD_COUNT_MAX         1155
#define IDC_DGT_BOARD_APPLY_COUNT       1156
#define IDC_GROUP_ALARM_DELAY_TIME      1156
#define IDC_DGT_STATION_YIELD           1157
#define IDC_DGT_ALARM_DELAY_TIME        1157
#define IDC_DGT_MACHINE_YIELD           1158
#define IDC_DGT_LINE_YIELD              1159
#define IDC_EDIT_ALARM_REPARE           1160
#define IDC_DGT_STATION_APPLY_COUNT     1160
#define IDC_EDIT_ALARM_TITLE            1161
#define IDC_BTN_PCBOX_CHECK             1161
#define IDC_BTN_PCBOX_QUERY             1162
#define IDC_GROUP_SHIFTER_LENGTH        1162
#define IDC_EDIT_BOARD_DATA             1163
#define IDC_CST_RACK_REAR_1_R           1163
#define IDC_GROUP_SHIFTER_Z             1163
#define IDC_CST_RACK_FRONT_1_R          1164
#define IDC_GROUP_SHIFTER_X             1164
#define IDC_CST_RACK_REAR_2_R           1165
#define IDC_GROUP_BUFFER                1165
#define IDC_EDIT_EQUIP_ID               1166
#define IDC_EDIT_FTP_PATH               1166
#define IDC_CST_RACK_FRONT_2_R          1166
#define IDC_GROUP_MOT_BARCODE           1166
#define IDC_EDIT_EQUIP_NO               1167
#define IDC_GROUP_MOT_SHIFTER_LENGTH    1167
#define IDC_DGT_OFFLINE_TEST_TIME       1167
#define IDC_EDIT_FTPID                  1168
#define IDC_GROUP_MOT_SHIFTER_Z         1168
#define IDC_EDIT_FTPPASSWORD            1169
#define IDC_GROUP_MOT_SHIFTER_X         1169
#define IDC_EDIT_FTPPORT                1170
#define IDC_GROUP_MOT_BUFFER            1170
#define IDC_RADIO_REAR_BUFFER           1171
#define IDC_EDIT_OPERATION_DISPLAY      1171
#define IDC_RADIO_TRAY_SUPPLY           1171
#define IDC_EDIT_PASS_CHG_NEW           1172
#define IDC_RADIO_FRONT_BUFFER          1172
#define IDC_RADIO_TRAY_TRANSFER         1172
#define IDC_EDIT_PASS_CHG_OLD           1173
#define IDC_RADIO_REAR_SHIFTER          1173
#define IDC_RADIO_SORT_ROBOT            1173
#define IDC_EDIT_PASS_CHG_VERIFY        1174
#define IDC_RADIO_FRONT_SHIFTER         1174
#define IDC_BTN_EMO_STOP                1174
#define IDC_RADIO_AIR_BLOW              1174
#define IDC_EDIT_PASS_CHK_DATA          1175
#define IDC_RADIO_BARCODE               1175
#define IDC_MSG_FRONT_REAR              1175
#define IDC_RADIO_TRAY_UNLOADER         1175
#define IDC_CUSTOM_TIME                 1176
#define IDC_MSG_MOT_X_POS               1176
#define IDC_GROUP_EJECTOR               1177
#define IDC_IO_LEFT_UP                  1178
#define IDC_IO_LEFT_DN                  1179
#define IDC_IO_RIGHT_UP                 1180
#define IDC_IO_RIGHT_DN                 1181
#define IDC_BTN_EJECTOR_UP              1182
#define IDC_BTN_EJECTOR_DN              1183
#define IDC_EDIT_TESTERPORT             1184
#define IDC_EDIT_PORT_NMACHINE          1184
#define IDC_GROUP_EJECTOR_REPEAT_CNT    1184
#define IDC_EDIT_PORT_ECSERVER          1184
#define IDC_EDIT_PORT_BPC               1185
#define IDC_RADIO_CNT_1                 1185
#define IDC_EDIT_LDPORT_ECSERVER        1185
#define IDC_RADIO_CNT_10                1186
#define IDC_LABEL_EVENT_MSG             1186
#define IDC_END_DATE                    1186
#define IDC_EDIT_PORT_ECSERVER2         1186
#define IDC_EDIT_PORT_NEXT              1186
#define IDC_FTPIPADDRESS                1187
#define IDC_RADIO_CNT_50                1187
#define IDC_IO_RACK_POWER_1             1187
#define IDC_END_TIME                    1187
#define IDC_GIF_ALARM                   1188
#define IDC_RADIO_CNT_100               1188
#define IDC_IO_RACK_POWER_2             1188
#define IDC_GROUP_NEXT_APCT_SET         1188
#define IDC_GIF_EXIT                    1189
#define IDC_IO_RACK_POWER_3             1189
#define IDC_MSG_IPADDRESS_APCT          1189
#define IDC_IO_BC_UP                    1189
#define IDC_GIF_INFO                    1190
#define IDC_IO_RACK_POWER_4             1190
#define IDC_MSG_PORT_APCT               1190
#define IDC_IO_BC_DN                    1190
#define IDC_IPADDRESS_APCT              1191
#define IDC_RADIO_POS_1                 1191
#define IDC_EDIT_PORT_APCT              1192
#define IDC_RADIO_POS_2                 1192
#define IDC_GIF_M_MESSAGE               1193
#define IDC_BTN_IP_SAVE_APCT            1193
#define IDC_RADIO_POS_3                 1193
#define IDC_GIF_MENU                    1194
#define IDC_BTN_PORT_SAVE_APCT          1194
#define IDC_RADIO_POS_4                 1194
#define IDC_GIF_MESSAGE                 1195
#define IDC_BTN_CONNECT_APCT            1195
#define IDC_GIF_SELECT                  1196
#define IDC_BTN_TEST_APCT               1196
#define IDC_GROUP_APCT_TYPE             1197
#define IDC_RADIO_APCT_TYPE_FRONT       1198
#define IDC_EDIT_SERVER_PORT_APCT       1199
#define IDC_LABEL_EQP_NO                1199
#define IDC_LABEL_EQP_ID                1199
#define IDC_GROUP_ALARM_INFO            1200
#define IDC_MSG_SERVER_PORT_APCT        1200
#define IDC_MSG_EQP_NO                  1200
#define IDC_MSG_EQP_ID                  1200
#define IDC_BTN_SERVER_PORT_SAVE_APCT   1201
#define IDC_LABEL_MACHINE_POS           1201
#define IDC_BTN_BC_UP                   1201
#define IDC_EDIT_SERVER_PORT_FMACHINE   1202
#define IDC_MSG_MACHINE_POS             1202
#define IDC_BTN_BC_DN                   1202
#define IDC_GROUP_OFFLINE_TEST_TIME     1202
#define IDC_MSG_SERVER_PORT_FMACHINE    1203
#define IDC_LABEL_DEVICE_NAME           1203
#define IDC_RADIO1                      1203
#define IDC_GROUP_BARCODE               1204
#define IDC_BTN_SERVER_PORT_SAVE_FMACHINE 1204
#define IDC_MSG_DEVICE_NAME             1204
#define IDC_RADIO2                      1204
#define IDC_RADIO_APCT_TYPE_REAR        1205
#define IDC_BUTTON5                     1205
#define IDC_GROUP_BARCODE_ERROR_MODE    1206
#define IDC_RADIO_APCT_TYPE_ALONE       1206
#define IDC_BUTTON6                     1206
#define IDC_GROUP_BYPASS                1207
#define IDC_BUTTON7                     1207
#define IDC_BTN_FILE_EDITOR             1207
#define IDC_GROUP_BARCODE_READ_COUNT    1208
#define IDC_BUTTON8                     1208
#define IDC_GROUP_BARCODE_READ_ERR_CNT  1209
#define IDC_BUTTON9                     1209
#define IDC_BTN_IO_MOVE_1               1209
#define IDC_BUTTON10                    1210
#define IDC_BTN_IO_MOVE_2               1210
#define IDC_BUTTON11                    1211
#define IDC_BTN_IO_MOVE_3               1211
#define IDC_GROUP_BOARD                 1212
#define IDC_BUTTON12                    1212
#define IDC_BTN_IO_MOVE_4               1212
#define IDC_BUTTON13                    1213
#define IDC_BTN_IO_MOVE_5               1213
#define IDC_CHK_DEBUG                   1214
#define IDC_BTN_IO_MOVE_6               1214
#define IDC_BTN_SEARCH_BOARDOFF         1215
#define IDC_BTN_IO_MOVE_7               1215
#define IDC_COMBO_LOTNAME               1216
#define IDC_BTN_IO_MOVE_8               1216
#define IDC_GROUP_SITE_TEST_INFO        1217
#define IDC_BTN_IO_MOVE_9               1217
#define IDC_CST_LOT_TIME                1218
#define IDC_BTN_IO_MOVE_10              1218
#define IDC_CST_SITE_TEST_INFO          1219
#define IDC_BTN_IO_MOVE_11              1219
#define IDC_RADIO_COUNT_INFO            1220
#define IDC_BTN_IO_MOVE_12              1220
#define IDC_GROUP_BUZZER                1221
#define IDC_GROUP_UPH                   1221
#define IDC_CUSTOM4                     1222
#define IDC_CST_UPH                     1222
#define IDC_CUSTOM_REAR_BUFFER          1222
#define IDC_RADIO_TEST_RESULT           1223
#define IDC_CUSTOM_RETEST_BUFFER        1223
#define IDC_GROUP_LOT_NO                1224
#define IDC_CUSTOM_FRONT_BUFFER         1224
#define IDC_CUSTOM1                     1225
#define IDC_CHK_RACK_SKIP_1             1225
#define IDC_CUSTOM_REJECT_BUFFER_L      1225
#define IDC_CUSTOM_REJECT_BUFFER        1225
#define IDC_CST_SORTER_SCRAP_LIST       1225
#define IDC_CUSTOM_FILE_INFO            1225
#define IDC_GROUP_DATA                  1226
#define IDC_CHK_RACK_SKIP_2             1226
#define IDC_CUSTOM_UPPER_TRAY_L         1226
#define IDC_CUSTOM_TRAY_1               1226
#define IDC_CST_SORTER_SCRAP_INFO       1226
#define IDC_GROUP_DATA_BACKUP           1227
#define IDC_RADIO_BOARD                 1227
#define IDC_CHK_RACK_SKIP_3             1227
#define IDC_CUSTOM_LOWER_TRAT_L         1227
#define IDC_CUSTOM_TRAY_2               1227
#define IDC_CST_SERVER_SCRAP_INFO       1227
#define IDC_GROUP_DEVICE                1228
#define IDC_CHK_RACK_SKIP_4             1228
#define IDC_GALMG_TEST                  1228
#define IDC_CST_ROUTER_SORTER_SCRAP_INFO 1228
#define IDC_CHECK_CONTROL_ENABLE        1229
#define IDC_CUSTOM_LOB_BUFFER_L         1229
#define IDC_CUSTOM_LOB_BUFFER           1229
#define IDC_CST_FCT_HANDLER_SCRAP_INFO  1229
#define IDC_CHECK_SHOW_DETAIL_LIST      1230
#define IDC_CUSTOM_LOB_BUFFER_R         1230
#define IDC_CST_PCT_SORTER_SCRAP_INFO   1230
#define IDC_CUSTOM_UPPER_TRAY_R         1231
#define IDC_CUSTOM_LOWER_TRAY_R         1232
#define IDC_GROUP_END_DATE              1233
#define IDC_CHK_FAIL_NTO                1233
#define IDC_CUSTOM_REJECT_BUFFER_R      1233
#define IDC_CUSTOM_CUSTOMER_BUFFER      1233
#define IDC_GROUP_EQP_SET               1234
#define IDC_CHK_FAIL_BTO                1234
#define IDC_EDIT_REAR_SITE              1234
#define IDC_GROUP_FTP_SET               1235
#define IDC_CHK_FAIL_HTO                1235
#define IDC_EDIT_FRONT_SITE             1235
#define IDC_BUTTON19                    1236
#define IDC_CHK_FAIL_FAIL               1236
#define IDC_BTN_SET_SITE                1236
#define IDC_EDIT_REAR_STATION           1237
#define IDC_EDIT_FRONT_STATION          1238
#define IDC_BTN_DRAW_SITE               1239
#define IDC_BTN_BACK_SITE               1240
#define IDC_EDIT_ALOT_NO                1242
#define IDC_CUSTOM_AIR_BLOW             1242
#define IDC_EDIT_BLOT_NO                1243
#define IDC_CUSTOM_LOT_INFO             1243
#define IDC_EDIT_CLOT_NO                1244
#define IDC_CUSTOM_WORK_CNT             1244
#define IDC_CUSTOM_DAILY_YIELD_INFO     1244
#define IDC_GROUP_INPUT                 1245
#define IDC_STATIC_LOT_CHK              1245
#define IDC_CUSTOM_BIN_CNT              1245
#define IDC_CUSTOM_LOT_YIELD_INFO       1245
#define IDC_GROUP_INTERFACE             1246
#define IDC_BTN_LOT_NO_LOAD             1246
#define IDC_GROUP_LOT_INFO              1246
#define IDC_BTN_LOT_NO_SET              1247
#define IDC_CUSTOM_PICKER               1247
#define IDC_STATIC_LAST_MODULE          1248
#define IDC_GROUP_B_LOT_INFO            1248
#define IDC_DGT_EJECT_COUNT             1249
#define IDC_GROUP_WORK_CNT              1249
#define IDC_GROUP_DAILY_YIELD_INFO      1249
#define IDC_BTN_BUFFERDB_DELETE         1250
#define IDC_GROUP_BIN_CNT               1250
#define IDC_GROUP_LOT_YIELD_INFO        1250
#define IDC_BUTTON14                    1251
#define IDC_GROUP_REAR_BUFFER           1251
#define IDC_BUTTON15                    1252
#define IDC_GROUP_FRONT_BUFFER          1252
#define IDC_BUTTON16                    1253
#define IDC_GROUP_LOB_BUFFER            1253
#define IDC_GROUP_KEYPAD                1254
#define IDC_EDIT_SEQ_MSG                1254
#define IDC_GROUP_PICKER                1254
#define IDC_GROUP_LAMP_ALARM            1255
#define IDC_GROUP_REJECT_BUFFER         1255
#define IDC_GROUP_IO                    1255
#define IDC_GROUP_LAMP_FLICKER_TIME     1256
#define IDC_GROUP_UPPER_TRAY            1256
#define IDC_LABEL_LOB                   1256
#define IDC_GROUP_LAMP_INITIAL          1257
#define IDC_GROUP_LOWER_TRAY            1257
#define IDC_LABEL_PICKER                1257
#define IDC_CUSTOM_BUFFER               1257
#define IDC_GROUP_LAMP_LOCK             1258
#define IDC_GROUP_AIR_BLOW_BOX          1258
#define IDC_LABEL_TITLE                 1258
#define IDC_GROUP_LAMP_LOTEND           1259
#define IDC_CUSTOM_B_LOT_INFO           1259
#define IDC_GROUP_SORTER_SCRAP_LIST     1259
#define IDC_GROUP_LAMP_RUN              1260
#define IDC_GROUP_BUTTON_SETTING        1260
#define IDC_GROUP_SORTER_SCRAP_INFO     1260
#define IDC_GROUP_LAMP_SELFCHECK        1261
#define IDC_LABEL_TRAY_1                1261
#define IDC_GROUP_QUESTION              1261
#define IDC_GROUP_LAMP_STOP             1262
#define IDC_LABEL_TRAY_2                1262
#define IDC_BTN_NO                      1262
#define IDC_GROUP_LAMP_WARNING          1263
#define IDC_LABEL_REJECT_BUFFER         1263
#define IDC_GROUP_ROUTER_SORTER_SCRAP_INFO 1263
#define IDC_GROUP_LAMP_CHANGE_TIME      1264
#define IDC_EDIT_REAR_BUFFER            1264
#define IDC_CHK_LENGTH_CHANGE           1264
#define IDC_GROUP_FCT_HANDLER_SCRAP_INFO 1264
#define IDC_EDIT_RETEST                 1265
#define IDC_GROUP_SERVER_SCRAP_LIST     1265
#define IDC_EDIT_FRONT_BUFFER           1266
#define IDC_GROUP_PCT_SORTER_SCRAP_INFO 1266
#define IDC_EDIT_LOB_TRAY               1267
#define IDC_BTN_TRACK_OUT               1267
#define IDC_EDIT_PICKER_INFO            1268
#define IDC_BTN_ADD_FAIL                1268
#define IDC_EDIT_REJECT_BUFFER          1269
#define IDC_GROUP_ADD_SCRAP_TO_SERVER   1269
#define IDC_LABEL_CUSTOMER_BUFFER       1270
#define IDC_GROUP_ADD_4200_SCRAP_TO_SERVER 1270
#define IDC_EDIT_UPPER_TRAY             1271
#define IDC_LABEL_SERIAL                1271
#define IDC_MSG_RUN                     1272
#define IDC_BTN_ADD_4200                1272
#define IDC_EDIT_LOWER_TRAY             1273
#define IDC_GROUP_ADD_4201_SCRAP_TO_SERVER 1273
#define IDC_LABEL_REAR_BUFFER           1274
#define IDC_GROUP_ADD_4202_SCRAP_TO_SERVER 1274
#define IDC_MSG_STOP                    1275
#define IDC_BTN_ADD_4201                1275
#define IDC_MSG_ALARM                   1276
#define IDC_BTN_ADD_4202                1276
#define IDC_LABEL_RETEST_BUFFER         1277
#define IDC_LABEL_AS_SC                 1277
#define IDC_DGT_RUN                     1278
#define IDC_LABEL_A4200_SC              1278
#define IDC_LABEL_FRONT_BUFFER          1279
#define IDC_LABEL_A4201_SC              1279
#define IDC_LABEL_A4202_SC              1280
#define IDC_DGT_STOP                    1281
#define IDC_EDIT_SERIAL                 1281
#define IDC_DGT_ALARM                   1282
#define IDC_EDIT_AS_SC                  1282
#define IDC_BTN_SCRAP_INFO              1282
#define IDC_EDIT_A4200_SC               1283
#define IDC_CHK_EDIT                    1283
#define IDC_EDIT_A4201_SC               1284
#define IDC_BTN_LOTNO_INIT              1284
#define IDC_EDIT_A4202_SC               1285
#define IDC_GROUP_FILE_INFO             1285
#define IDC_BTN_PAD_MINUS               1286
#define IDC_GROUP_MOTOR_POWER_1         1297
#define IDC_GROUP_MOTOR_POWER_2         1298
#define IDC_GROUP_MOTOR_POWER_3         1299
#define IDC_GROUP_MOTOR_POWER_4         1300
#define IDC_GROUP_MOTOR_POWER_5         1301
#define IDC_GROUP_MOTOR_SPEED_RATE      1304
#define IDC_GROUP_MOTOR_SPEED_SET       1305
#define IDC_GROUP_MOTOR_VARIABLE_SPEED_SET 1306
#define IDC_GROUP_OPERATION_LIST        1308
#define IDC_GROUP_OPERATION_TYPE        1309
#define IDC_GROUP_OUTPUT                1310
#define IDC_GROUP_PASS_CHG              1313
#define IDC_GROUP_PASS_CHK              1314
#define IDC_GROUP_PASSWORD_CHANGE       1315
#define IDC_GROUP_PCB_SIZE              1317
#define IDC_GROUP_PREV_ALARM            1328
#define IDC_GROUP_RETEST                1333
#define IDC_GROUP_RETEST_BUFFER         1333
#define IDC_GROUP_RETEST_COUNT          1334
#define IDC_GROUP_STAMP_LIMIT           1346
#define IDC_GROUP_STAMP_CHECK           1347
#define IDC_GROUP_START_DATE            1347
#define IDC_CUSTOM_MOTOR_POS            1347
#define IDC_GROUP_STATIC_ELECTRICITY_CHECK_GAP 1348
#define IDC_GROUP_GROUND_VALUE          1349
#define IDC_GROUP_GROUND_ALLOW          1350
#define IDC_CUSTOM_INPUT                1350
#define IDC_CUSTOM_OUTPUT               1352
#define IDC_GROUP_TESTER_SET            1353
#define IDC_GROUP_MOTOR                 1355
#define IDC_GROUP_TOWERLAMP             1362
#define IDC_GROUP_MOVE                  1371
#define IDC_BTN_EXIT                    1375
#define IDC_TAB_MOTOR_PART              1376
#define IDC_GROUP_MOTOR_PART            1377
#define IDC_MOTOR_IMG                   1378
#define IDC_BTN_LEFT                    1379
#define IDC_BTN_HOME                    1380
#define IDC_BTN_RIGHT                   1381
#define IDC_GROUP_PART                  1382
#define IDC_CUSTOM_MOTOR_PART           1383
#define IDC_BMP_VIEW                    1384
#define IDC_IMAGE_ALARM                 1385
#define IDC_GROUP_PART_INFORMATION      1385
#define IDC_INFO_MESSAGE                1386
#define IDC_BTN_IO                      1386
#define IDC_CHK_AXIS_1                  1387
#define IDC_CHK_AXIS_2                  1388
#define IDC_CUSTOM_MOTOR_INFO           1389
#define IDC_BTN_MANUAL                  1389
#define IDC_IO_HOME_1                   1399
#define IDC_IO_HOME_2                   1400
#define IDC_CHK_AXIS_3                  1400
#define IDC_IO_HOME_3                   1401
#define IDC_GROUP_AXIS_INFO             1401
#define IDC_IO_HOME_4                   1402
#define IDC_CHK_AXIS_4                  1402
#define IDC_IO_HOME_5                   1403
#define IDC_CHK_AXIS_5                  1403
#define IDC_CHK_AXIS_6                  1404
#define IDC_IO_ML_1                     1405
#define IDC_CHK_AXIS_7                  1405
#define IDC_IO_ML_2                     1406
#define IDC_CHK_AXIS_8                  1406
#define IDC_IO_ML_3                     1407
#define IDC_CHK_AXIS_9                  1407
#define IDC_IO_ML_4                     1408
#define IDC_CHK_AXIS_10                 1408
#define IDC_IO_ML_5                     1409
#define IDC_IO_MOTOR_ALARM_1            1411
#define IDC_IO_MOTOR_ALARM_2            1412
#define IDC_IO_MOTOR_ALARM_3            1413
#define IDC_IO_MOTOR_ALARM_4            1414
#define IDC_IO_MOTOR_ALARM_5            1415
#define IDC_IO_MOTOR_POWER_1            1417
#define IDC_IO_MOTOR_POWER_2            1418
#define IDC_IO_MOTOR_POWER_3            1419
#define IDC_IO_MOTOR_POWER_4            1420
#define IDC_IO_MOTOR_POWER_5            1421
#define IDC_IO_BARCODE_SAFETY           1422
#define IDC_IO_PL_1                     1423
#define IDC_IO_PL_2                     1424
#define IDC_IO_PL_3                     1425
#define IDC_IO_PL_4                     1426
#define IDC_IO_PL_5                     1427
#define IDC_JOG_MINUS_1                 1449
#define IDC_JOG_MINUS_2                 1450
#define IDC_JOG_MINUS_3                 1451
#define IDC_JOG_MINUS_4                 1452
#define IDC_JOG_MINUS_5                 1453
#define IDC_JOG_PLUS_1                  1457
#define IDC_JOG_PLUS_2                  1458
#define IDC_JOG_PLUS_3                  1459
#define IDC_JOG_PLUS_4                  1460
#define IDC_JOG_PLUS_5                  1461
#define IDC_LABEL_PCB_X                 1518
#define IDC_LABEL_PCB_Y                 1519
#define IDC_LAMP_ALARM                  1552
#define IDC_LAMP_INITIAL                1553
#define IDC_LAMP_LOCK                   1554
#define IDC_LAMP_LOTEND                 1555
#define IDC_LAMP_RUN                    1556
#define IDC_LAMP_SELFCHECK              1557
#define IDC_LAMP_STOP                   1558
#define IDC_LAMP_WARNING                1559
#define IDC_LIST_DEVICE_TYPE            1563
#define IDC_LIST_MENU                   1564
#define IDC_LIST_OPERATION_FILE         1565
#define IDC_MONTHCAL_OPERATION          1570
#define IDC_MSG_ALARM_CODE              1575
#define IDC_MSG_ALARM_REPARE            1578
#define IDC_MSG_ALARM_TITLE             1580
#define IDC_MSG_ALARM_TYPE              1581
#define IDC_MSG_BOARD                   1608
#define IDC_MSG_CURRENT_POS_1           1632
#define IDC_MSG_CURRENT_POS_2           1633
#define IDC_MSG_CURRENT_POS_3           1634
#define IDC_MSG_CURRENT_POS_4           1635
#define IDC_MSG_CURRENT_POS_5           1636
#define IDC_MSG_EQUIP_ID                1641
#define IDC_MSG_EQUIP_NO                1642
#define IDC_MSG_EXIT                    1643
#define IDC_MSG_FTPID                   1645
#define IDC_MSG_FTPIPADDRESS            1646
#define IDC_MSG_FTPPASSWORD             1647
#define IDC_MSG_FTPPORT                 1648
#define IDC_MSG_KEYPAD_LIMIT            1671
#define IDC_MSG_KEYPAD_TITLE            1672
#define IDC_MSG_LOT_END                 1699
#define IDC_MSG_M_MESSAGE               1705
#define IDC_MSG_MANUAL_RATE             1709
#define IDC_MSG_MENU                    1710
#define IDC_MSG_MESSAGE                 1711
#define IDC_MSG_OPERATION_FILE          1737
#define IDC_MSG_OPERATION_FILE_NAME     1738
#define IDC_MSG_PARTIAL                 1740
#define IDC_MSG_PASS_CHG                1741
#define IDC_MSG_PASS_CHK                1742
#define IDC_MSG_RUN_RATE                1778
#define IDC_MSG_SAVING                  1780
#define IDC_MSG_TESTERIPADDRESS         1825
#define IDC_MSG_IPADDRESS_NMACHINE      1825
#define IDC_MSG_IPADDRESS_ECSERVER      1825
#define IDC_MSG_TESTERPORT              1826
#define IDC_MSG_PORT_NMACHINE           1826
#define IDC_MSG_PORT_ECSERVER           1826
#define IDC_MSG_IPADDRESS_BPC           1827
#define IDC_MSG_TRAY_X                  1827
#define IDC_MSG_PORT_BPC                1828
#define IDC_MSG_TRAY_Y                  1828
#define IDC_MSG_LDPORT_ECSERVER         1829
#define IDC_MSG_IPADDRESS_ECSERVER2     1830
#define IDC_MSG_IPADDRESS_NEXT          1830
#define IDC_MSG_PORT_ECSERVER2          1831
#define IDC_MSG_PORT_NEXT               1831
#define IDC_PAD_EQUIP_ID                1886
#define IDC_PAD_EQUIP_NO                1887
#define IDC_PICTURE_ABOUT               1890
#define IDC_RADIO_ALARM                 1913
#define IDC_RADIO_INTERFACE             1959
#define IDC_RADIO_MACHINE               1981
#define IDC_RADIO_OPERATION             1984
#define IDC_RADIO_PASS_NEW              2001
#define IDC_RADIO_PASS_OLD              2002
#define IDC_RADIO_PASS_VERIFY           2003
#define IDC_RADIO_WITH_DVC              2061
#define IDC_RADIO_WITHOUT_DVC           2062
#define IDC_RADIO_FTP_MODE              2063
#define IDC_RADIO_LOCAL_MODE            2064
#define IDC_SELECT_MESSAGE              2092
#define IDC_START_DATE                  2101
#define IDC_START_TIME                  2102
#define IDC_TESTERIPADDRESS             2115
#define IDC_IPADDRESS_NMACHINE          2115
#define IDC_IPADDRESS_ECSERVER          2115
#define IDC_IPADDRESS_BPC               2116
#define IDC_IPADDRESS_ECSERVER2         2116
#define IDC_IPADDRESS_NEXT              2116
#define IDC_TITLE_PASS_CHK              2120
#define IDSAVEOK                        2227
#define IDC_MSG_FTP_PATH                2600
#define IDC_PAD_FTP_PATH                2601
#define IDC_GROUP_GROUND_TEST           2604
#define IDC_GROUP_ELECTROSTATIC_TEST    2604
#define IDC_BTN_TEST                    2609
#define IDC_BTN_TEST_NMACHINE           2609
#define IDC_BTN_TEST_ECSERVER           2609
#define IDC_BTN_FTP_TEST                2610
#define IDC_BTN_TEST_BPC                2610
#define IDC_BTN_TEST_ECSERVER2          2610
#define IDC_BTN_TEST_NEXT               2610
#define IDC_RADIO_LOT                   2614
#define IDC_RADIO_PART                  2615
#define IDC_RADIO_ALL                   2616
#define IDC_BTN_STAMP_COUNT_RESET       2621
#define IDC_BTN_SEARCH2_ALARM           2623
#define IDC_GROUP_TIME                  3565
#define IDC_BTN_IO_OPEN                 3772
#define IDC_GROUP_IO_PART               3773
#define IDC_BTN_IO_PART_OPEN            3774
#define IDC_BTN_MOTOR_PART_OPEN         3776
#define IDC_GROUP_MOTOR_POS             3777
#define IDC_BTN_MOTOR_POS_OPEN          3778
#define IDC_BTN_TIME_OPEN               3780
#define ID_MAIN                         32771
#define ID_BASIC                        32772
#define ID_SETTING                      32773
#define ID_WAIT                         32774
#define ID_MOTOR                        32775
#define ID_LIST                         32776
#define ID_IO                           32777
#define ID_LEVEL                        32778
#define ID_SAVE                         32779
#define ID_ALARM                        32780
#define ID_ABOUT                        32781
#define ID_ADMIN                        32782
#define ID_RESET                        32783
#define ID_LOCK                         32784
#define ID_EXIT                         32785
#define ID_SET_MAINTENANCE              32786
#define ID_SET_TESTREFERENCE            32787
#define ID_SET_INTERFACE                32788
#define ID_MOT_BUFFER                   32789
#define ID_MOT_SHIFTER                  32790
#define ID_MOT_TOTAL                    32791
#define ID_MOT_SPEED                    32792
#define ID_LIST_OPER                    32793
#define ID_LIST_DATAVIEW                32794
#define ID_LIST_STEP                    32795
#define ID_EMPTY                        32796
#define ID_MOT_TEACH                    32802
#define ID_FILE_EDITOR                  32803
#define ID_SET_BARCODE                  32804
#define IDD_SCREEN_SET_BARCODE          32805
#define ID_SET_NETWORK                  32806
#define IDD_SCREEN_SET_NETWORK          32807

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        252
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1287
#define _APS_NEXT_SYMED_VALUE           146
#endif
#endif
